import { SETUP1, SETUP2, SETUP3, SETUP4, SETUP5, SETUP6 } from '../../public/assets/import';

export const setupConfig = [
  {
    id: 1,
    head: 'Setup BY DONS',
    img: SETUP5,
    text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Autem libero qui eum deleniti eligendi molestias nulla, id illum dolor aliquam facilis ut animi. Iure amet molestias ipsam earum sunt ex?',
    date: '06',
    month: 'JAN',
    simple: 'Setup Simple',
    from: 'From Pinterest',
  },
  {
    id: 2,
    head: 'Setup BY DONS',
    img: SETUP2,
    text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Autem libero qui eum deleniti eligendi molestias nulla, id illum dolor aliquam facilis ut animi. Iure amet molestias ipsam earum sunt ex?',
    date: '09',
    month: 'FEB',
    simple: 'Setup Simple',
    from: 'Pinterest',
  },
  {
    id: 3,
    head: 'Setup BY CONAN',
    img: SETUP3,
    text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Autem libero qui eum deleniti eligendi molestias nulla, id illum dolor aliquam facilis ut animi. Iure amet molestias ipsam earum sunt ex?',
    date: '10',
    month: 'MAR',
    simple: 'Setup Simple',
    from: 'From Pinterest',
  },
  {
    id: 4,
    head: 'Setup BY CHRISTINE',
    img: SETUP4,
    text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Autem libero qui eum deleniti eligendi molestias nulla, id illum dolor aliquam facilis ut animi. Iure amet molestias ipsam earum sunt ex?',
    date: '30',
    month: 'DES',
    simple: 'Setup Simple',
    from: 'From Pinterest',
  },
  {
    id: 5,
    head: 'Setup BY JOSEP',
    img: SETUP1,
    text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Autem libero qui eum deleniti eligendi molestias nulla, id illum dolor aliquam facilis ut animi. Iure amet molestias ipsam earum sunt ex?',
    date: '20',
    month: 'SEP',
    simple: 'Setup Simple',
    from: 'From Pinterest',
  },
  {
    id: 6,
    head: 'Setup BY DONS',
    img: SETUP6,
    text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Autem libero qui eum deleniti eligendi molestias nulla, id illum dolor aliquam facilis ut animi. Iure amet molestias ipsam earum sunt ex?',
    date: '20',
    month: 'SEP',
    simple: 'Setup Simple',
    from: 'From Pinterest',
  },
];
